name: Go Build Example

on:
  push:
    branches:
      - main

env:
  FILE_NAME: hello-server

jobs:
  BuildGo:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Build Go for Linux
      run: go build ${{ env.FILE_NAME }}.go

    - name: Build Go for Windows
      run: GOOS=windows GOARCH=amd64 go build ${{ env.FILE_NAME }}.go

    - name: Upload artifact for linux
      uses: actions/upload-artifact@v1
      with:
        name: linux
        path: ./${{ env.FILE_NAME }}

    - name: Upload artifact for windows
      uses: actions/upload-artifact@v1
      with:
        name: windows
        path: ./${{ env.FILE_NAME }}.exe
